version: '3'
services:
  java-sleuth1:
    build: .
    ports:
      - "8080:8080"
    environment:
      - server.port=8080
      - java-server=http://java-sleuth2:8081
      - go-server=http://go-sleuth3:8082
      - spring.application.name=JavaSleuth1
  java-sleuth2:
    build: .
    ports:
      - "8081:8081"
    environment:
      - server.port=8081
      - java-server=http://java-sleuth1:8081
      - go-server=http://go-sleuth3:8082
      - spring.application.name=JavaSleuth2
  go-sleuth3:
    build: ../go
    ports:
      - "8082:8082"